function [ driver_table ] = getdrivertable()
%GETDRIVER Returns a Table of driver details

driver_name = {'Lewis Hamilton', ...
'Sebastian Vettel', ...
'Max Verstappen', ...
'Daniel Ricciardo', ...
'Kimi Raikkonen', ...
'Valtteri Bottas', ...
'Carlos Sainz Jr', ...
'Kevin Magnussen', ...
'Sergio Perez', ...
'Esteban Ocon', ...
'Romain Grosjean', ...
'Nico Hulkenberg', ...
'Jolyon Palmer', ...
'Felipe Massa', ...
'Marcus Ericsson', ...
'Fernando Alonso', ...
'Daniil Kvyat', ...
'Lance Stroll', ...
'Antonio Giovinazzi', ...
'Stoffel Vandoorne', ...
'Pascal Wehrlein'}';

driver_team = {'Mercedes', ...
'Ferrari', ...
'Red Bull', ...
'Red Bull', ...
'Ferrari', ...
'Mercedes', ...
'Toro Rosso', ...
'Haas', ...
'Force India', ...
'Force India', ...
'Haas', ...
'Renault', ...
'Renault', ...
'Williams', ...
'Sauber', ...
'McLaren', ...
'Toro Rosso', ...
'Williams', ...
'Sauber', ...
'McLaren', ...
'Sauber'}';

driver_cost = [30, ...
29, ...
27, ...
27, ...
26, ...
28, ...
22, ...
17, ...
20, ...
16, ...
18, ...
19, ...
16, ...
24, ...
15, ...
20, ...
17, ...
16, ...
15, ...
15, ...
15]';

driver_table = table(driver_name, driver_team, driver_cost);

end

